/** @type {import('tailwindcss').Config} */
// Premium "Amethyst" design tokens — ported 1:1 from h5_ui numbered mockups
// (12._home, 13._chat_list, 14._me, 15._asset_library, …). Preflight is OFF so
// the legacy Lumina pages (styled by styles.css) keep working untouched.
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        outline: "#7b7487",
        "on-primary-fixed-variant": "#5a00c6",
        "primary-container": "#7c3aed",
        error: "#ba1a1a",
        "surface-tint": "#732ee4",
        "tertiary-fixed": "#6ffbbe",
        surface: "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#ccc3d8",
        "surface-container-high": "#e2e7ff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#eaddff",
        "tertiary-container": "#007650",
        "on-surface-variant": "#4a4455",
        "on-surface": "#131b2e",
        "on-primary-fixed": "#25005a",
        "surface-bright": "#faf8ff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#002113",
        "on-primary-container": "#ede0ff",
        "surface-variant": "#dae2fd",
        secondary: "#0058be",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "surface-dim": "#d2d9f4",
        primary: "#630ed4",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#fefcff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#d2bbff",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-highest": "#dae2fd",
        "on-error": "#ffffff",
        "on-tertiary-container": "#76ffc2",
        "on-background": "#131b2e",
        "inverse-surface": "#283044",
        "secondary-container": "#2170e4",
        "inverse-primary": "#d2bbff",
        "surface-container": "#eaedff",
        tertiary: "#005b3d",
        "error-container": "#ffdad6",
        background: "#faf8ff",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed": "#001a42",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "touch-target-min": "44px",
        base: "8px",
        "margin-mobile": "20px",
        gutter: "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "PingFang SC", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "PingFang SC", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    forms({ strategy: "class" }),
    containerQueries,
  ],
};
