/** @type {import('tailwindcss').Config} */
// Premium "Amethyst" design tokens — surface/on-surface colors use CSS variables
// (see premium.css) so light/dark theme switches without per-page overrides.
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        white: "rgb(var(--color-white-rgb) / <alpha-value>)",
        outline: "rgb(var(--premium-outline-rgb) / <alpha-value>)",
        "on-primary-fixed-variant": "#5a00c6",
        "primary-container": "#7c3aed",
        error: "#ba1a1a",
        "surface-tint": "#732ee4",
        "tertiary-fixed": "rgb(var(--premium-tertiary-fixed-rgb) / <alpha-value>)",
        surface: "rgb(var(--premium-surface-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--premium-surface-container-lowest-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--premium-outline-variant-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--premium-surface-container-high-rgb) / <alpha-value>)",
        "on-secondary": "#ffffff",
        "primary-fixed": "rgb(var(--premium-primary-fixed-rgb) / <alpha-value>)",
        "tertiary-container": "#007650",
        "on-surface-variant": "rgb(var(--premium-on-surface-variant-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--premium-on-surface-rgb) / <alpha-value>)",
        "on-primary-fixed": "#25005a",
        "surface-bright": "rgb(var(--premium-surface-bright-rgb) / <alpha-value>)",
        "on-error-container": "#93000a",
        "secondary-fixed": "rgb(var(--premium-secondary-fixed-rgb) / <alpha-value>)",
        "on-tertiary-fixed": "#002113",
        "on-primary-container": "#ede0ff",
        "surface-variant": "rgb(var(--premium-surface-variant-rgb) / <alpha-value>)",
        secondary: "#0058be",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "surface-dim": "rgb(var(--premium-surface-dim-rgb) / <alpha-value>)",
        primary: "#630ed4",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#adc6ff",
        "on-secondary-container": "#fefcff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#d2bbff",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#004395",
        "surface-container-highest": "rgb(var(--premium-surface-container-highest-rgb) / <alpha-value>)",
        "on-error": "#ffffff",
        "on-tertiary-container": "#76ffc2",
        "on-background": "rgb(var(--premium-on-background-rgb) / <alpha-value>)",
        "inverse-surface": "rgb(var(--premium-inverse-surface-rgb) / <alpha-value>)",
        "secondary-container": "#2170e4",
        "inverse-primary": "#d2bbff",
        "surface-container": "rgb(var(--premium-surface-container-rgb) / <alpha-value>)",
        tertiary: "#005b3d",
        "error-container": "#ffdad6",
        background: "rgb(var(--premium-background-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--premium-surface-container-low-rgb) / <alpha-value>)",
        "on-secondary-fixed": "#001a42",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "touch-target-min": "44px",
        base: "8px",
        "margin-mobile": "20px",
        gutter: "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "PingFang SC", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "PingFang SC", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms")({ strategy: "class" }),
    require("@tailwindcss/container-queries"),
  ],
};
