import { useState, useRef, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { ChevronLeft, MoreHorizontal, Leaf, Bot, Volume2, Search, Send, Keyboard, Info, CheckCircle2, Mic, Loader } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { useGameStore } from "../../stores/gameStore";

export default function RoleplayChat() {
  const navigate = useNavigate();
  const [input, setInput] = useState("");
  const feedEndRef = useRef<HTMLDivElement>(null);
  
  const { createSession, currentSession, sendTurn, feedItems, currentHud, turnLoading } = useGameStore();
  const searchParams = new URLSearchParams(window.location.search);
  const storyId = searchParams.get('story') || 'qingyun';

  // We rely on createSession if we don't have an ID, or loadSession if we do.
  // For simplicity, we just create a new session if one isn't loaded.
  useEffect(() => {
    if (!currentSession || currentSession.game_type !== "roleplay") {
      createSession("roleplay", undefined, { story_id: storyId });
    }
  }, [storyId, createSession, currentSession]);

  useEffect(() => {
    feedEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [feedItems, turnLoading, currentHud]);

  const handleSend = async (actionType = "message", payload: any = undefined) => {
    if (!currentSession) return;
    if (actionType === "message" && !payload && !input.trim()) return;

    const userInput = payload || input;
    if (!payload) setInput("");
    
    await sendTurn(currentSession.id, actionType, userInput, { action_type: actionType });
  };

  const view = currentSession?.view as Record<string, any> || {};
  const currentChapter = view.current_chapter || 0;
  const chapterTitle = view.chapter_title || "当前章节";
  const totalChapters = view.total_chapters || 1;

  // The HUD contains learning points generated by AI
  const hud = currentHud as Record<string, any> | null;
  const whyPoints = hud?.why_this_expression as any[] | undefined;

  // Find choices from the latest feed items
  const choicesItem = feedItems.slice().reverse().find(i => i.type === "choices");
  const choices = choicesItem?.choices as any[] | undefined;

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="premium w-full h-full bg-[#fdf2f8] flex flex-col font-sans relative text-[#111827] overflow-hidden"
    >
      {/* Header */}
      <header className="px-4 pt-[env(safe-area-inset-top,20px)] h-16 flex items-center justify-between bg-[#fdf2f8]/90 backdrop-blur-md z-50 shrink-0">
        <button onClick={() => navigate(-1)} className="w-8 h-8 flex items-center justify-center text-gray-700 active:scale-95 transition-transform">
          <ChevronLeft size={24} />
        </button>
        <div className="flex items-center gap-2 flex-1 justify-center">
          <h1 className="font-bold text-[16px] text-[#111827]">{currentSession?.title || "Roleplay"}</h1>
        </div>
        <button className="w-8 h-8 flex items-center justify-center text-gray-700">
          <MoreHorizontal size={20} />
        </button>
      </header>

      {/* Chapters Strip */}
      <div className="px-4 py-2 bg-white flex items-center gap-2 shrink-0 border-b border-gray-100 overflow-x-auto no-scrollbar">
        {Array.from({ length: totalChapters }).map((_, idx) => (
          <button 
            key={idx}
            className={`px-4 py-1.5 text-[11px] rounded-full transition-all shrink-0 border ${
              idx === currentChapter 
                ? "font-bold bg-pink-100 text-pink-600 border-pink-200" 
                : "font-medium text-gray-400 bg-gray-50 border-gray-100"
            }`}
          >
            T{idx + 1} {idx === currentChapter ? chapterTitle : `章节 ${idx+1}`}
          </button>
        ))}
      </div>

      {/* Main Scrollable Area */}
      <main className="flex-1 overflow-y-auto w-full flex flex-col no-scrollbar bg-[#fdfdfdf] pb-48">
        
        {/* Learning HUD */}
        <AnimatePresence>
          {hud && (
            <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} className="p-4 flex gap-3 overflow-x-auto no-scrollbar shrink-0">
              <div className="min-w-[200px] flex-1 bg-pink-50/80 border border-pink-100/50 rounded-2xl p-3 shadow-sm relative">
                <div className="flex items-center gap-1.5 text-pink-600 mb-2">
                  <Leaf size={14} />
                  <span className="text-[11px] font-bold">自然表达</span>
                </div>
                <h3 className="font-bold text-[14px] text-[#111827] leading-tight mb-1">{hud.main_expression}</h3>
                <p className="text-[11px] text-gray-500 mb-2">{hud.meaning_native}</p>
                {hud.vocabulary && (
                  <div className="flex gap-1 flex-wrap mt-2">
                    {hud.vocabulary.map((v: string, i: number) => (
                      <span key={i} className="inline-flex items-center gap-1 bg-white text-pink-600 text-[9px] font-bold px-1.5 py-0.5 rounded border border-pink-200">
                        {v}
                      </span>
                    ))}
                  </div>
                )}
              </div>

              {whyPoints && whyPoints.length > 0 && (
                <div className="min-w-[200px] flex-1 bg-indigo-50/80 border border-indigo-100/50 rounded-2xl p-3 shadow-sm relative">
                  <div className="flex items-center gap-1.5 text-indigo-600 mb-2">
                    <Bot size={14} />
                    <span className="text-[11px] font-bold">为什么这么写？</span>
                  </div>
                  <div className="flex flex-col gap-2">
                    {whyPoints.map((wp: any, i: number) => (
                      <div key={i} className="flex flex-col">
                        <span className="font-bold text-[11px] text-[#111827]">{wp.point}</span>
                        <span className="text-[10px] text-gray-500 leading-snug">{wp.explanation}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </motion.div>
          )}
        </AnimatePresence>

        {/* Chat Area */}
        <div className="px-4 flex flex-col gap-5 pb-4 mt-2">
          
          {!currentSession && (
            <div className="flex justify-center my-10"><Loader className="animate-spin text-pink-400" /></div>
          )}

          {feedItems.map((item, idx) => {
            if (item.type === "chapter_start") {
               return (
                  <motion.div key={idx} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="flex justify-center my-4">
                    <div className="bg-gradient-to-r from-orange-100 to-rose-100 text-rose-800 px-6 py-2 rounded-full text-[12px] font-bold shadow-sm border border-rose-200">
                      章节 {item.chapter as string} 开启
                    </div>
                  </motion.div>
               );
            }

            if (item.type === "narrative") {
              return (
                <motion.div key={idx} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="flex justify-center my-2">
                  <div className="bg-white/80 backdrop-blur-sm border border-gray-200/50 px-4 py-3 rounded-2xl shadow-sm w-full flex flex-col gap-1.5">
                    <p className="text-[12px] text-gray-700 leading-relaxed font-serif">
                      {(item.text_zh as string) || item.text}
                    </p>
                  </div>
                </motion.div>
              );
            }

            if (item.type === "user_action") {
              return (
                <motion.div key={idx} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="flex justify-end">
                  <div className="flex flex-col items-end">
                    <div className="bg-gradient-to-r from-pink-400 to-rose-400 text-white px-4 py-2.5 rounded-2xl rounded-tr-sm shadow-sm max-w-[85%] relative">
                      <p className="text-[13px] leading-relaxed break-words">{item.text}</p>
                    </div>
                  </div>
                </motion.div>
              );
            }

            if (item.type === "character") {
              return (
                <motion.div key={idx} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} className="flex justify-start gap-3">
                  <div className="w-10 h-10 rounded-full bg-pink-100 flex items-center justify-center shrink-0 shadow-sm overflow-hidden border border-white">
                    <span className="text-pink-400 font-bold text-[10px]">{(item.speaker as string).slice(0,2)}</span>
                  </div>
                  <div className="flex flex-col items-start max-w-[80%]">
                    <div className="flex items-center gap-2 mb-1 ml-1">
                      <span className="text-[10px] text-gray-500 font-bold">{item.speaker as string}</span>
                      {!!item.emotion && (
                        <span className="text-[9px] bg-pink-50 text-pink-500 px-1.5 rounded-full border border-pink-100">{item.emotion as string}</span>
                      )}
                    </div>
                    <div className="bg-white border border-pink-50 px-4 py-3 rounded-2xl rounded-tl-sm shadow-sm flex flex-col gap-2 relative">
                      <p className="text-[13px] text-[#111827] font-medium leading-relaxed pr-6">
                        {item.text as string}
                      </p>
                      <button className="absolute top-3 right-3 text-pink-400 active:scale-95 transition-transform">
                        <Volume2 size={16} />
                      </button>
                    </div>
                  </div>
                </motion.div>
              );
            }

            return null;
          })}
          
          {turnLoading && (
            <motion.div initial={{opacity:0}} animate={{opacity:1}} className="flex items-center gap-2 text-pink-400 text-[12px] justify-center mt-2">
              <Loader size={14} className="animate-spin" /> AI生成中...
            </motion.div>
          )}

          <div ref={feedEndRef} />
        </div>
      </main>

      {/* Bottom Input Area */}
      <div className="fixed bottom-[max(env(safe-area-inset-bottom,0px),0px)] w-full max-w-md mx-auto bg-white/95 backdrop-blur-md z-40 pb-4 pt-3 border-t border-gray-100 rounded-t-3xl shadow-[0_-10px_40px_rgba(0,0,0,0.05)]">
        
        {/* Choices Strip */}
        {!turnLoading && choices && choices.length > 0 && (
          <div className="flex flex-col gap-2 px-4 mb-3">
            {choices.map((ch: any, idx: number) => (
               <button key={idx} onClick={() => handleSend("user_action", ch.text)} className="w-full text-left bg-[#f8fafc] border border-[#f1f5f9] hover:bg-pink-50 hover:border-pink-200 transition-colors px-4 py-2.5 rounded-2xl shadow-sm flex items-start gap-3 group">
                 <span className="w-6 h-6 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center text-[12px] font-bold shrink-0 mt-0.5">{String.fromCharCode(65 + idx)}</span>
                 <div className="flex flex-col">
                   <span className="text-[13px] font-bold text-[#111827] group-hover:text-pink-600 transition-colors">{ch.text}</span>
                   {ch.text_en && <span className="text-[10px] text-gray-400 mt-0.5">"{ch.text_en}"</span>}
                 </div>
               </button>
            ))}
          </div>
        )}

        {/* Custom Input Bar */}
        <div className="px-4 flex items-center gap-3 mt-1">
          <button className="w-10 h-10 flex items-center justify-center text-gray-400 hover:text-pink-500 bg-gray-50 rounded-full shrink-0 transition-colors border border-gray-100">
            <Keyboard size={18} />
          </button>
          <div className="flex-1 bg-gray-50 flex items-center px-4 py-2.5 rounded-full border border-gray-100 focus-within:border-pink-300 focus-within:ring-2 focus-within:ring-pink-100 transition-all">
            <input
              type="text"
              placeholder="自定义回复..."
              className="flex-1 bg-transparent text-[13px] outline-none placeholder:text-gray-400 text-[#111827] min-w-0"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleSend("user_action")}
              disabled={turnLoading}
            />
            <button className="text-gray-400 hover:text-pink-500 ml-2">
              <Mic size={16} />
            </button>
          </div>
          <button 
            disabled={!input.trim() || turnLoading}
            onClick={() => handleSend("user_action")}
            className="w-10 h-10 flex items-center justify-center bg-gradient-to-r from-pink-500 to-rose-500 text-white rounded-full shadow-md shadow-pink-500/30 disabled:opacity-50 disabled:shadow-none active:scale-95 transition-all shrink-0"
          >
            <Send size={16} className="ml-0.5 -mt-0.5" />
          </button>
        </div>
      </div>
    </motion.div>
  );
}
