"""initial schema

Revision ID: 62c29e271eca
Revises: 
Create Date: 2026-06-13 13:24:08.391233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c29e271eca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('provider_type', sa.String(length=40), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cost_weight', sa.Float(), nullable=False),
    sa.Column('fallback_provider', sa.String(length=120), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('language_pair', sa.String(length=40), nullable=False),
    sa.Column('pattern_type', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grammar_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grammar_patterns_code'), ['code'], unique=False)

    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('membership_level', sa.String(length=40), nullable=False),
    sa.Column('membership_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=80), nullable=False),
    sa.Column('native_language', sa.String(length=20), nullable=False),
    sa.Column('target_language', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('voice_seconds', sa.Integer(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ai_memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_ai_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_ai_memories_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_ai_memories_user_id'), ['user_id'], unique=False)

    op.create_table('user_mastery',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=40), nullable=False),
    sa.Column('item_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('language_code', sa.String(length=20), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_mastery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_mastery_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_mastery_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('native_language', sa.String(length=20), nullable=False),
    sa.Column('target_languages', sa.JSON(), nullable=False),
    sa.Column('primary_target_language', sa.String(length=20), nullable=False),
    sa.Column('current_level', sa.String(length=20), nullable=False),
    sa.Column('learning_goals', sa.JSON(), nullable=False),
    sa.Column('favorite_topics', sa.JSON(), nullable=False),
    sa.Column('correction_style', sa.String(length=40), nullable=False),
    sa.Column('coach_style', sa.String(length=40), nullable=False),
    sa.Column('explanation_language', sa.String(length=20), nullable=False),
    sa.Column('ui_language', sa.String(length=20), nullable=False),
    sa.Column('voice_preference', sa.String(length=60), nullable=False),
    sa.Column('speaking_confidence_score', sa.Float(), nullable=False),
    sa.Column('writing_confidence_score', sa.Float(), nullable=False),
    sa.Column('grammar_level_score', sa.Float(), nullable=False),
    sa.Column('vocabulary_level_score', sa.Float(), nullable=False),
    sa.Column('fluency_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_language', sa.String(length=20), nullable=False),
    sa.Column('translated_content', sa.Text(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('expression_versions', sa.JSON(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('thoughts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('final_content_native', sa.Text(), nullable=False),
    sa.Column('final_content_target', sa.Text(), nullable=False),
    sa.Column('mind_graph', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thoughts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thoughts_user_id'), ['user_id'], unique=False)

    op.create_table('voice_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('cost_estimate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('expression_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('thought_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_language', sa.String(length=20), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('patterns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thought_id'], ['thoughts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expression_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expression_assets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expression_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expression_assets_user_id'))

    op.drop_table('expression_assets')
    with op.batch_alter_table('voice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_sessions_user_id'))

    op.drop_table('voice_sessions')
    with op.batch_alter_table('thoughts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thoughts_user_id'))

    op.drop_table('thoughts')
    with op.batch_alter_table('conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_messages_conversation_id'))

    op.drop_table('conversation_messages')
    op.drop_table('user_profiles')
    with op.batch_alter_table('user_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_mastery_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_mastery_item_id'))

    op.drop_table('user_mastery')
    with op.batch_alter_table('user_ai_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_ai_memories_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_ai_memories_memory_type'))

    op.drop_table('user_ai_memories')
    op.drop_table('usage_logs')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_name'))

    op.drop_table('prompt_templates')
    with op.batch_alter_table('grammar_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammar_patterns_code'))

    op.drop_table('grammar_patterns')
    op.drop_table('ai_providers')
    # ### end Alembic commands ###
