"""add_all_enterprise_models_v1_2

Revision ID: 6736a5fde22f
Revises: c4d5e6f7a8b9
Create Date: 2026-06-13 21:20:24.659525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6736a5fde22f'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('daily_ai_dialogue', sa.Integer(), nullable=False),
    sa.Column('daily_voice_minutes', sa.Integer(), nullable=False),
    sa.Column('daily_freeze_count', sa.Integer(), nullable=False),
    sa.Column('asset_limit', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membership_plans_level'), ['level'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('ai_provider_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('task_types', sa.JSON(), nullable=False),
    sa.Column('cost_per_1k_input', sa.Float(), nullable=False),
    sa.Column('cost_per_1k_output', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_provider_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_provider_models_provider_id'), ['provider_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_admin_user_id'), ['admin_user_id'], unique=False)

    op.create_table('data_deletion_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_deletion_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_deletion_requests_user_id'), ['user_id'], unique=False)

    op.create_table('login_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_logs_user_id'), ['user_id'], unique=False)

    op.create_table('match_analysis_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_analysis_reports_user_id'), ['user_id'], unique=False)

    op.create_table('match_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_user_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_recommendations_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('match_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=False),
    sa.Column('to_user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_requests_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_requests_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('moderation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('content_id', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privacy_consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('consent_type', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('privacy_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_privacy_consents_user_id'), ['user_id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_template_id'), ['template_id'], unique=False)

    op.create_table('realtime_session_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('realtime_session_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_realtime_session_logs_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)

    op.create_table('user_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blocker_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_blocks_blocked_id'), ['blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_blocks_blocker_id'), ['blocker_id'], unique=False)

    op.create_table('user_communication_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reasoning_depth', sa.Float(), nullable=False),
    sa.Column('knowledge_breadth', sa.Float(), nullable=False),
    sa.Column('reflection_ability', sa.Float(), nullable=False),
    sa.Column('emotional_maturity', sa.Float(), nullable=False),
    sa.Column('communication_quality', sa.Float(), nullable=False),
    sa.Column('response_style', sa.String(length=40), nullable=False),
    sa.Column('conversation_language', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_communication_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_communication_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('user_match_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('target_languages', sa.JSON(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('lifestyle', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_match_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('match_mode', sa.String(length=40), nullable=False),
    sa.Column('visibility', sa.String(length=40), nullable=False),
    sa.Column('profile_completeness', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=True),
    sa.Column('permission_id', sa.String(length=36), nullable=True),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_permissions_user_id'), ['user_id'], unique=False)

    op.create_table('user_personality_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mbti', sa.String(length=8), nullable=False),
    sa.Column('big_five', sa.JSON(), nullable=False),
    sa.Column('constellation', sa.String(length=40), nullable=False),
    sa.Column('bazi', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_personality_tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_personality_tests_user_id'), ['user_id'], unique=True)

    op.create_table('user_privacy_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('match_profile_visible', sa.Boolean(), nullable=False),
    sa.Column('data_retention_days', sa.Integer(), nullable=False),
    sa.Column('allow_analytics', sa.Boolean(), nullable=False),
    sa.Column('public_scope', sa.String(length=40), nullable=False),
    sa.Column('match_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_value_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('emotional_values', sa.JSON(), nullable=False),
    sa.Column('lifestyle_prefs', sa.JSON(), nullable=False),
    sa.Column('relationship_goals', sa.JSON(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('match_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_user_id', sa.String(length=36), nullable=False),
    sa.Column('to_user_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['match_recommendations.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_feedback_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_feedback_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('mind_graph_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('thought_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=40), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thought_id'], ['thoughts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mind_graph_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mind_graph_nodes_user_id'), ['user_id'], unique=False)

    op.create_table('pronunciation_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('voice_session_id', sa.String(length=36), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=False),
    sa.Column('spoken_text', sa.Text(), nullable=False),
    sa.Column('fluency_score', sa.Float(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['voice_session_id'], ['voice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pronunciation_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pronunciation_scores_user_id'), ['user_id'], unique=False)

    op.create_table('thought_arguments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thought_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thought_id'], ['thoughts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thought_arguments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thought_arguments_thought_id'), ['thought_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thought_arguments_user_id'), ['user_id'], unique=False)

    op.create_table('thought_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thought_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thought_id'], ['thoughts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thought_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thought_facts_thought_id'), ['thought_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thought_facts_user_id'), ['user_id'], unique=False)

    op.create_table('thought_values',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thought_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thought_id'], ['thoughts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thought_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thought_values_thought_id'), ['thought_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thought_values_user_id'), ['user_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('thought_id', sa.String(length=36), nullable=True),
    sa.Column('parent_topic_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('pro_view', sa.Text(), nullable=False),
    sa.Column('con_view', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['thought_id'], ['thoughts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_creator_id'), ['creator_id'], unique=False)

    op.create_table('circle_rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('room_type', sa.String(length=40), nullable=False),
    sa.Column('allowed_languages', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circle_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circle_rooms_creator_id'), ['creator_id'], unique=False)

    op.create_table('mind_graph_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['mind_graph_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['mind_graph_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mind_graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mind_graph_edges_source_node_id'), ['source_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mind_graph_edges_target_node_id'), ['target_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mind_graph_edges_user_id'), ['user_id'], unique=False)

    op.create_table('topic_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_recommendations_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_recommendations_user_id'), ['user_id'], unique=False)

    op.create_table('topic_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('pro_view', sa.Text(), nullable=False),
    sa.Column('con_view', sa.Text(), nullable=False),
    sa.Column('creator_user_id', sa.String(length=36), nullable=True),
    sa.Column('parent_topic_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_versions_topic_id'), ['topic_id'], unique=False)

    op.create_table('circle_ai_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('summary_type', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['circle_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circle_ai_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circle_ai_summaries_room_id'), ['room_id'], unique=False)

    op.create_table('circle_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['circle_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circle_members_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circle_members_user_id'), ['user_id'], unique=False)

    op.create_table('circle_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_language', sa.String(length=20), nullable=False),
    sa.Column('translated_content', sa.Text(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['circle_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circle_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circle_messages_room_id'), ['room_id'], unique=False)

    op.create_table('circle_collected_viewpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('collector_user_id', sa.String(length=36), nullable=False),
    sa.Column('original_user_id', sa.String(length=36), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('my_understanding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collector_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['circle_messages.id'], ),
    sa.ForeignKeyConstraint(['original_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['circle_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('circle_collected_viewpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circle_collected_viewpoints_collector_user_id'), ['collector_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circle_collected_viewpoints_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circle_collected_viewpoints_room_id'), ['room_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_collected_viewpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circle_collected_viewpoints_room_id'))
        batch_op.drop_index(batch_op.f('ix_circle_collected_viewpoints_message_id'))
        batch_op.drop_index(batch_op.f('ix_circle_collected_viewpoints_collector_user_id'))

    op.drop_table('circle_collected_viewpoints')
    with op.batch_alter_table('circle_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circle_messages_room_id'))

    op.drop_table('circle_messages')
    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circle_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_circle_members_room_id'))

    op.drop_table('circle_members')
    with op.batch_alter_table('circle_ai_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circle_ai_summaries_room_id'))

    op.drop_table('circle_ai_summaries')
    with op.batch_alter_table('topic_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_versions_topic_id'))

    op.drop_table('topic_versions')
    with op.batch_alter_table('topic_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_topic_recommendations_topic_id'))

    op.drop_table('topic_recommendations')
    with op.batch_alter_table('mind_graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mind_graph_edges_user_id'))
        batch_op.drop_index(batch_op.f('ix_mind_graph_edges_target_node_id'))
        batch_op.drop_index(batch_op.f('ix_mind_graph_edges_source_node_id'))

    op.drop_table('mind_graph_edges')
    with op.batch_alter_table('circle_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circle_rooms_creator_id'))

    op.drop_table('circle_rooms')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_creator_id'))

    op.drop_table('topics')
    with op.batch_alter_table('thought_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thought_values_user_id'))
        batch_op.drop_index(batch_op.f('ix_thought_values_thought_id'))

    op.drop_table('thought_values')
    with op.batch_alter_table('thought_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thought_facts_user_id'))
        batch_op.drop_index(batch_op.f('ix_thought_facts_thought_id'))

    op.drop_table('thought_facts')
    with op.batch_alter_table('thought_arguments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thought_arguments_user_id'))
        batch_op.drop_index(batch_op.f('ix_thought_arguments_thought_id'))

    op.drop_table('thought_arguments')
    with op.batch_alter_table('pronunciation_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pronunciation_scores_user_id'))

    op.drop_table('pronunciation_scores')
    with op.batch_alter_table('mind_graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mind_graph_nodes_user_id'))

    op.drop_table('mind_graph_nodes')
    with op.batch_alter_table('match_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_feedback_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_match_feedback_from_user_id'))

    op.drop_table('match_feedback')
    op.drop_table('user_value_profiles')
    op.drop_table('user_privacy_settings')
    with op.batch_alter_table('user_personality_tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_personality_tests_user_id'))

    op.drop_table('user_personality_tests')
    with op.batch_alter_table('user_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_permissions_user_id'))

    op.drop_table('user_permissions')
    op.drop_table('user_match_settings')
    op.drop_table('user_match_profiles')
    with op.batch_alter_table('user_communication_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_communication_profiles_user_id'))

    op.drop_table('user_communication_profiles')
    with op.batch_alter_table('user_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_user_blocks_blocked_id'))

    op.drop_table('user_blocks')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))

    op.drop_table('reports')
    with op.batch_alter_table('realtime_session_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_realtime_session_logs_user_id'))

    op.drop_table('realtime_session_logs')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_template_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('privacy_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_privacy_consents_user_id'))

    op.drop_table('privacy_consents')
    op.drop_table('moderation_events')
    with op.batch_alter_table('match_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_requests_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_match_requests_from_user_id'))

    op.drop_table('match_requests')
    with op.batch_alter_table('match_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_recommendations_user_id'))
        batch_op.drop_index(batch_op.f('ix_match_recommendations_target_user_id'))

    op.drop_table('match_recommendations')
    with op.batch_alter_table('match_analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_analysis_reports_user_id'))

    op.drop_table('match_analysis_reports')
    with op.batch_alter_table('login_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_logs_user_id'))

    op.drop_table('login_logs')
    with op.batch_alter_table('data_deletion_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_deletion_requests_user_id'))

    op.drop_table('data_deletion_requests')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_admin_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_provider_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_provider_models_provider_id'))

    op.drop_table('ai_provider_models')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    with op.batch_alter_table('membership_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membership_plans_level'))

    op.drop_table('membership_plans')
    # ### end Alembic commands ###
